lights:
 light_1:
  position:
    x: 5.0
    y: 7.0
    z: 2.9
  color:
    r: 0.988
    g: 0.980
    b: 0.964
  ambient_strength: 0.4
  diffuse_strength: 0.8
  specular_strength: 1.
  attenuation_radius: 10.

 light_2:
  position:
    x: 8.5
    y: 7.0
    z: 2.9
  color:
    r: 0.988
    g: 0.980
    b: 0.964
  ambient_strength: 0.4
  diffuse_strength: 0.8
  specular_strength: 1.
  attenuation_radius: 10.