include:
  - package://overworld/config/env/adream_visual.yaml
  - package://overworld/config/env/adream_lights.yaml

adream_walls:
  orientation:
    z: 1.57

adream_hall_floor:
  orientation:
    z: 1.57

adream_expe_floor:
  orientation:
    z: 1.57

adream_window_h10_1:
  visual_only: true
  orientation:
    z: 1.57

adream_window_h10_2:
  visual_only: true
  scale:
    y: 1.022
  position:
    x: -2.8639
    y: 8.2988
    z: 1.4249

adream_window_door_outside_3x3_1:
  visual_only: true
  orientation:
    z: 1.57
  position:
    x: 11.573
    y: 15.98
    z: 1.5938

adream_window_door_outside_3x3_2:
  visual_only: true
  orientation:
    z: 1.57
  position:
    x: 11.573
    y: 6.0135
    z: 1.5938

adream_window_door_outside_3x3_3:
  visual_only: true
  orientation:
    z: 1.57
  position:
    x: 11.573
    y: -3.9512
    z: 1.5938
    
adream_window_outside_3x3_1:
  visual_only: true
  orientation:
    z: 1.57
  position:
    x: 11.571
    y: 1.0355
    z: 1.5932

adream_window_outside_3x3_2:
  visual_only: true
  orientation:
    z: 1.57
  position:
    x: 11.571
    y: 11.001
    z: 1.5929

adream_window_h22_1:
  visual_only: true
  position:
    x: 5.0627
    y: -1.0579
    z: 1.7611

adream_window_h22_2:
  visual_only: true
  position:
    x: 5.0627
    y: -5.3393
    z: 1.7611

adream_window_h22_3:
  visual_only: true
  orientation:
    z: 1.57
  scale:
    y: 1.12
  position:
    x: 3.95
    y: -0.04475
    z: 1.7611

adream_window_h20_3:
  visual_only: true
  position:
    x: 10.06
    y: 18.805
    z: 1.5531

adream_window_h20_4:
  visual_only: true
  position:
    x: 8.8243
    y: 18.508
    z: 1.5531

adream_window_h20_5:
  visual_only: true
  position:
    x: 7.584
    y: 18.508
    z: 1.5531

adream_window_h20_6:
  visual_only: true
  position:
    x: 6.3587
    y: 18.505
    z: 1.5531

adream_window_h20_7:
  visual_only: true
  orientation:
    z: 1.57

adream_window_h20_8:
  visual_only: true
  position:
    x: -0.060667
    y: 1.2035
    z: 1.8868

adream_window_h20_9:
  visual_only: true
  position:
    x: -0.060667
    y: 3.6972
    z: 1.8868

adream_window_door_1:
  visual_only: true
  orientation:
    z: 3.1415
  position:
    x: -0.060667
    y: 6.0788
    z: 1.4258

adream_window_door_2:
  visual_only: true
  orientation:
    z: -1.57
  position:
    x: -5.2078
    y: 8.2955
    z: 1.4258

adream_window_h20_8:
  visual_only: true
  position:
    x: -0.060667
    y: 1.2035
    z: 1.8868

adream_window_h20_9:
  visual_only: true
  position:
    x: -0.060667
    y: 3.6972
    z: 1.8868

adream_appartment:
  orientation:
    z: 1.57

adream_door_h21_1:
  visual_only: true
  position:
    x: 1.03963
    y: -0.00339
    z: 1.0725
  orientation:
    z: 1.57

adream_door_h21_2:
  visual_only: true
  position:
    x: 5.09035
    y: 18.4801
    z: 1.0725
  orientation:
    z: 1.57

adream_door_h21_3:
  visual_only: true
  position:
    x: 0.932577
    y: 18.4514
    z: 1.0725
  orientation:
    z: 1.57

adream_door_h16:
  visual_only: true
  position:
    x: -0.152311
    y: 22.3506
    z: 1.0725
  orientation:
    z: 3.14159

adream_door_h12:
  visual_only: true
  position:
    x: -11.5018
    y: 11.6701
    z: 1.0725
  orientation:
    z: 2.51327

adream_door_h14:
  visual_only: true
  position:
    x: -6.56428
    y: 9.44934
    z: 1.0725

adream_door_h13:
  visual_only: true
  position:
    x: -10.236
    y: 11.2895
    z: 1.0725
  orientation:
    z: -0.942478

adream_door_h11:
  visual_only: true
  position:
    x: -9.51151
    y: 14.0825
    z: 1.0725
  orientation:
    z: -0.942478
