adream_ff_walls:
  visual_only: true

adream_ff_floor:
  visual_only: true

adream_gg_roof:
  visual_only: true

adream_guard_rail:
  visual_only: true

window_h100_1:
  visual_only: true
  mesh: package://overworld/models/adream/windows/window_h100_1.obj

window_h100_2:
  visual_only: true
  mesh: package://overworld/models/adream/windows/window_h100_2.obj

window_h100_3:
  visual_only: true
  mesh: package://overworld/models/adream/windows/window_h100_3.obj

adream_tree:
  visual_only: true
  mesh: package://overworld/models/trees/Tree1_.obj
  scale:
    x: 0.4
    y: 0.4
    z: 0.3
  position:
    x: -3
    y: 4